services:
    mariadb:
        image: mariadb:10.11
        container_name: mariadb-container
        restart: always
        env_file: .env
        environment:
            MARIADB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 3306:3306
        volumes:
            - shared-mariadb-volume:/var/lib/mysql
        networks:
            - shared-networks

    postgresql:
        image: postgres:13.11
        container_name: postgres-container
        restart: always
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 5432:5432
        volumes:
            - shared-postgresql-volume:/var/lib/postgresql/data
        networks:
            - shared-networks

    mongodb:
        image: mongo:6.0.5
        container_name: mongodb-container
        restart: always
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${SERVICE_DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 27017:27017
        volumes:
            - shared-mongodb-volume:/data/db
            - shared-mongodb-volume:/data/configdb
        networks:
            - shared-networks

    redis:
        image: redis:7.0
        container_name: redis-container
        restart: always
        environment:
            TZ: Asia/Jakarta
        ports:
            - 6379:6379
        volumes:
            - shared-redis-volume:/data
        networks:
            - shared-networks

networks:
    shared-networks:
        driver: bridge
        external: true

volumes:
    shared-mariadb-volume:
        name: shared-mariadb-volume
        driver: local
    shared-postgresql-volume:
        name: shared-postgresql-volume
        driver: local
    shared-mongodb-volume:
        name: shared-mongodb-volume
        driver: local
    shared-redis-volume:
        name: shared-redis-volume
        driver: local
