services:
    mariadb:
        image: mariadb:10.11
        container_name: mariadb-container
        restart: always
        env_file: .env
        environment:
            MARIADB_ROOT_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 3306:3306
        volumes:
            - ./mariadb:/var/lib/mysql
        networks:
            - shared-networks
            - ruangprint-networks

    postgresql:
        image: postgres:13.11
        container_name: postgres-container
        restart: always
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${SERVICE_DB_PASS}
            TZ: Asia/Jakarta
        ports:
            - 5432:5432
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - shared-networks
            - ruangprint-networks

    mongodb:
        image: mongo:6.0.5
        container_name: mongodb-container
        restart: always
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${SERVICE_MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_MONGO_PASS}
            TZ: Asia/Jakarta
        ports:
            - 27017:27017
        volumes:
            - ./mongodb:/data/db
            - ./mongodb:/data/configdb
        networks:
            - shared-networks
            - ruangprint-networks

    redis:
        image: redis:7.0
        container_name: redis-container
        restart: always
        environment:
            TZ: Asia/Jakarta
        ports:
            - 6379:6379
        volumes:
            - ./redis:/data
        networks:
            - shared-networks
            - ruangprint-networks

networks:
    shared-networks:
        driver: bridge
        external: true
